const recommendationData2 = [
    {
        MangaTitle:"Return of the Mount Hua Sect",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/03/cover.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=40871",
MangaUrl:"https://www.asurascans.com/manga/1660333069-return-of-the-mount-hua-sect/",
MangaSynopsis:"Chung Myung, The 13th Disciple of the Mount Hua Sect, One of the 3 Great Swordsmen, Plum Blossom Sword Saint, defeated Chun Ma, who has brought destruction and disarray onto the world. After the battle, he breathes his last breath on top of the headquarter mountain of the Heavenly Demon Sect. He is reborn after 100 years in the body of a child. ……What? The Mount Hua Sect has fallen? What kind of nonsense is that!?",
_id:"return-of-the-mount-hua-sect",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:36 GMT",
    },
    {
        MangaTitle:"Damn Reincarnation",
        MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/06/Damn_ReincarnationCover003.png",
        MangaShortUrl:"https://www.asurascans.com/?p=107248",
        MangaUrl:"https://www.asurascans.com/manga/1660333069-damn-reincarnation/",
        MangaSynopsis:"[From the author of Worthless Regression]<br>Hamel, a warrior who traveled with his colleagues to exterminate the devil. Unfortunately, he died just before the battle with the devil started. “Yes.” What the hell? He was reborn as the descendant of his fellow warrior, Vermouth. The descendant from the bloodline of the great Vermouth, Hamel. No, he was now Eugene Lionhart. “It was already enough with me having the delusion that I was a genius in my past life. But… this… It’s… It’s incomparable.’ From a dying body to a new body, he has the achievement that he did not have in his previous life. And, a reincarnation of an unknown origin, the reality of living together with the demons. Facing a new world where everything is questionable. The journey of the unfinished previous life begins with Eugene’s body.",
        _id:"damn-reincarnation",
        _type:"asura",
        ScrapeDate:"Sun, 18 Sep 2022 05:48:42 GMT", 
    },
    {
        MangaTitle:"Reincarnation of the Suicidal Battle God",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/06/sogdobogdo.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=49050",
MangaUrl:"https://www.asurascans.com/manga/1660333069-reincarnation-of-the-suicidal-battle-god/",
MangaSynopsis:"A time travel action fantasy of the strongest of mankind. “Even if the disgusting gods gave me this chance, an opportunity is still an opportunity. Since they want to end up dead, I will kill them.” The last survivor of mankind, Zephyr. The fight with the demons ended in defeat and the gods gave him a chance to go back 10 years in time. The demons who took everything away from humans and the gods who treated humans as beings for sight-seeing. This time, I will tear them to pieces.",
_id:"reincarnation-of-the-suicidal-battle-god",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:33 GMT",
    },
    {
        MangaTitle:"Standard of Reincarnation",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/08/standardofReCover03.png",
MangaShortUrl:"https://www.asurascans.com/?p=119179",
MangaUrl:"https://www.asurascans.com/manga/1660333069-standard-of-reincarnation/",
MangaSynopsis:"The greatest martial family, Samion. Daven, a member of the Samion family, is a one-armed martial soldier without a right arm. Despite the ridicule and contempt he got for only having a left arm, he surpassed the direct line of the Samion family like a genius. However, he got betrayed by his family and parents in the end, thus meeting a poor end. But, he was reincarnated. “I have a right arm?” He had a new family tradition. A naturally gifted body. Experience from his past life. And the god Yulion with him as well. After his reincarnation, everything changed, and a new adventure started.",
_id:"standard-of-reincarnation",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:52 GMT",
    },
    {
        MangaTitle:"Reaper of the Drifting Moon",
        MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/07/Reaper-Moon-Cover-Animation_Compressed.gif",
        MangaShortUrl:"https://www.asurascans.com/?p=112859",
        MangaUrl:"https://www.asurascans.com/manga/1660333069-reaper-of-the-drifting-moon/",
        MangaSynopsis:"[From the author of Legend Of The Northern Blade.]<br>He’s in the deepest part of the Jianghu. Keep your eyes wide ,open if you do not wish to get dragged into the abyss.",
        _id:"reaper-of-the-drifting-moon",
        _type:"asura",
        ScrapeDate:"Wed, 07 Sep 2022 20:58:26 GMT",
    },
    {
        MangaTitle:"Player Who Returned 10,000 Years Later",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/07/Player10000yearsCover02_copy.png",
MangaShortUrl:"https://www.asurascans.com/?p=116341",
MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-returned-10000-years-later/",
MangaSynopsis:"One day, out of the blue, he falls into hell. All he has with him is his desire to live and predatory powers. From the thousandth hell to the nine thousandth, he‘s devoured tens and hundreds of thousands of demons, and even the seven archdukes bowed down to him. “Why do you wish to go back? Your Highness already has everything in hell.“ “Everything, my ass.“ There’s nothing to eat or enjoy here! Hell’s nothing but desolate land full of terrible demons! “I will return.“ After ten thousand long years, he finally returns to Earth.",
_id:"player-who-returned-10000-years-later",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:25 GMT",
    },
    {
        MangaTitle:"Solo Max-Level Newbie",
        MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/07/solomaxlevelnewbie.jpg",
        MangaShortUrl:"https://www.asurascans.com/?p=52313",
        MangaUrl:"https://www.asurascans.com/manga/1660333069-solo-max-level-newbie/",
        MangaSynopsis:"Jinhyuk, a gaming Nutuber, was the only person who saw the ending of the game [Tower of Trials].<br>However, when the game’s popularity declined, it became difficult for him to continue making a living as a gaming Nutuber.<br>Since he already saw the ending of the game, he was about to quit playing. But that day, [Tower of Trials] became reality, and Jinhyuk, who knew about every single thing in the game, took over everything faster than anyone possibly could! “I’ll show you what a true pro is like.”",
        _id:"solo-max-level-newbie",
        _type:"asura",
        ScrapeDate:"Wed, 07 Sep 2022 20:58:48 GMT", 
    },
    {
        MangaTitle:"Return of the Disaster-Class Hero",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/10/DisasterheroCover01.png",
MangaShortUrl:"https://www.asurascans.com/?p=61390",
MangaUrl:"https://www.asurascans.com/manga/1660333069-return-of-the-disaster-class-hero/",
MangaSynopsis:"I was the greatest hero on Earth.<br>“But he’s dead. How could the guy we’ve killed come back?”<br>“I dunno. But if he can come back, just let him.”<br>I really came back after 20 years?<br>“Why’re you so surprised? What? Did you do something to hurt your conscience?”<br>You bastards. Just you wait.",
_id:"return-of-the-disaster-class-hero",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:35 GMT",
    },
    {
        MangaTitle:"Reformation of the Deadbeat Noble",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/05/Cover1-3.png",
MangaShortUrl:"https://www.asurascans.com/?p=46495",
MangaUrl:"https://www.asurascans.com/manga/1660333069-reformation-of-the-deadbeat-noble/",
MangaSynopsis:"Airen Parreira is a boy who sleeps to run away from reality. People mocked him, calling him a ‘deadbeat’, but he had no wish to change. Until one day, he dreamt of a swordsman… It was a dream about a talentless man who had been training by swinging his sword for decades.",
_id:"reformation-of-the-deadbeat-noble",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:27 GMT",
    },
    {
        MangaTitle:"Swordmaster’s Youngest Son",
    MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/04/cover.jpg",
    MangaShortUrl:"https://www.asurascans.com/?p=96904",
    MangaUrl:"https://www.asurascans.com/manga/1660333069-swordmasters-youngest-son/",
    MangaSynopsis:"Jin Runcandel was the youngest son of Runcandel, the land’s most prestigious swordsman family…<br>And the biggest failure in Runcandel history.<br>He, who was kicked out miserably and came to a meaningless end, was given another chance.<br>“How do you want to use this power?”<br>“I want to use it for myself.”<br>Memories of his past life, overwhelming talent, and a contract with God…<br>The preparations to become the greatest are complete.",
    _id:"swordmasters-youngest-son",
    _type:"asura",
    ScrapeDate:"Wed, 07 Sep 2022 20:58:57 GMT",
    },
    {
        MangaTitle:"Player Who Can’t Level Up",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/02/Player_That_Cant_Level_Up_Title_Card_-_Barak_kopya.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=38049",
MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-cant-level-up/",
MangaSynopsis:"Gigyu Kim awakened as a player at the age of 18. He thought his life was on the track to success, climbing ‘the tower’ and closing ‘the gates’… But even after clearing the tutorial, he was level 1. He killed a goblin a day, and he was still level 1. Even after 5 years, he was still level 1. “Who would have thought that this kind of player would exist.” No one knew.",
_id:"player-who-cant-level-up",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:23 GMT",
    }
]
