
const recommendationData2 = [
    {
        title:"Return of the Mount Hua Sect",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/03/cover.jpg",
  shortURL:"https://www.asurascans.com/?p=40871",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-return-of-the-mount-hua-sect/",
  synopsis:"Chung Myung, The 13th Disciple of the Mount Hua Sect, One of the 3 Great Swordsmen, Plum Blossom Sword Saint, defeated Chun Ma, who has brought destruction and disarray onto the world. After the battle, he breathes his last breath on top of the headquarter mountain of the Heavenly Demon Sect. He is reborn after 100 years in the body of a child. ……What? The Mount Hua Sect has fallen? What kind of nonsense is that!?",
  slug:"return-of-the-mount-hua-sect",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:36 GMT",
  genre:
  {0:"Adventure",
  1:"Comedy",
  2:"Fantasy",
  3:"Martial Arts",
  4:"Rebirth",
  5:"Shounen"}
    },
    {
      title:"Damn Reincarnation",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/06/Damn_ReincarnationCover003.png",
  shortURL:"https://www.asurascans.com/?p=107248",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-damn-reincarnation/",
  synopsis:"[From the author of Worthless Regression]<br>Hamel, a warrior who traveled with his colleagues to exterminate the devil. Unfortunately, he died just before the battle with the devil started. “Yes.” What the hell? He was reborn as the descendant of his fellow warrior, Vermouth. The descendant from the bloodline of the great Vermouth, Hamel. No, he was now Eugene Lionhart. “It was already enough with me having the delusion that I was a genius in my past life. But… this… It’s… It’s incomparable.’ From a dying body to a new body, he has the achievement that he did not have in his previous life. And, a reincarnation of an unknown origin, the reality of living together with the demons. Facing a new world where everything is questionable. The journey of the unfinished previous life begins with Eugene’s body.",
  slug:"damn-reincarnation",
  _type:"asura",
  ScrapeDate:"Sun, 18 Sep 2022 05:48:42 GMT",
  genre:
  {0:"Action",
  1:"Adventure",
  2:"Fantasy",
  3:"Reincarnation",
  4:"Shounen"}
  },
    {
        title:"Reincarnation of the Suicidal Battle God",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/06/sogdobogdo.jpg",
  shortURL:"https://www.asurascans.com/?p=49050",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-reincarnation-of-the-suicidal-battle-god/",
  synopsis:"A time travel action fantasy of the strongest of mankind. “Even if the disgusting gods gave me this chance, an opportunity is still an opportunity. Since they want to end up dead, I will kill them.” The last survivor of mankind, Zephyr. The fight with the demons ended in defeat and the gods gave him a chance to go back 10 years in time. The demons who took everything away from humans and the gods who treated humans as beings for sight-seeing. This time, I will tear them to pieces.",
  slug:"reincarnation-of-the-suicidal-battle-god",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:33 GMT",
  genre:
  {0:"Adventure",
  1:"Fantasy",
  2:"Overpowered",
  3:"Returner",
  4:"Shounen"}
    },
    {
        title:"Standard of Reincarnation",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/08/standardofReCover03.png",
  shortURL:"https://www.asurascans.com/?p=119179",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-standard-of-reincarnation/",
  synopsis:"The greatest martial family, Samion. Daven, a member of the Samion family, is a one-armed martial soldier without a right arm. Despite the ridicule and contempt he got for only having a left arm, he surpassed the direct line of the Samion family like a genius. However, he got betrayed by his family and parents in the end, thus meeting a poor end. But, he was reincarnated. “I have a right arm?” He had a new family tradition. A naturally gifted body. Experience from his past life. And the god Yulion with him as well. After his reincarnation, everything changed, and a new adventure started.",
  slug:"standard-of-reincarnation",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:52 GMT",
  genre:
  {0:"Action",
  1:"Adventure",
  2:"Fantasy",
  3:"Martial Arts",
  4:"Reincarnation"}
    },
    {
        title:"Reaper of the Drifting Moon",
        coverURL:"https://www.asurascans.com/wp-content/uploads/2022/07/Reaper-Moon-Cover-Animation_Compressed.gif",
        shortURL:"https://www.asurascans.com/?p=112859",
        MangaUrl:"https://www.asurascans.com/manga/1660333069-reaper-of-the-drifting-moon/",
        synopsis:"[From the author of Legend Of The Northern Blade.]<br>He’s in the deepest part of the Jianghu. Keep your eyes wide ,open if you do not wish to get dragged into the abyss.",
        slug:"reaper-of-the-drifting-moon",
        _type:"asura",
        ScrapeDate:"Wed, 07 Sep 2022 20:58:26 GMT",
        genre:
  {0:"Action",
  1:"Fantasy",
  2:"Genius MC",
  3:"Martial Arts",
  4:"Murim"}
    },
    {
        title:"Player Who Returned 10,000 Years Later",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/07/Player10000yearsCover02_copy.png",
  shortURL:"https://www.asurascans.com/?p=116341",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-returned-10000-years-later/",
  synopsis:"One day, out of the blue, he falls into hell. All he has with him is his desire to live and predatory powers. From the thousandth hell to the nine thousandth, he‘s devoured tens and hundreds of thousands of demons, and even the seven archdukes bowed down to him. “Why do you wish to go back? Your Highness already has everything in hell.“ “Everything, my ass.“ There’s nothing to eat or enjoy here! Hell’s nothing but desolate land full of terrible demons! “I will return.“ After ten thousand long years, he finally returns to Earth.",
  slug:"player-who-returned-10000-years-later",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:25 GMT",
  genre:
  {0:"Action",
  1:"Adventure",
  2:"Comedy",
  3:"Fantasy"}
    },
    {
        title:"Solo Max-Level Newbie",
        coverURL:"https://www.asurascans.com/wp-content/uploads/2021/07/solomaxlevelnewbie.jpg",
        shortURL:"https://www.asurascans.com/?p=52313",
        MangaUrl:"https://www.asurascans.com/manga/1660333069-solo-max-level-newbie/",
        synopsis:"Jinhyuk, a gaming Nutuber, was the only person who saw the ending of the game [Tower of Trials].<br>However, when the game’s popularity declined, it became difficult for him to continue making a living as a gaming Nutuber.<br>Since he already saw the ending of the game, he was about to quit playing. But that day, [Tower of Trials] became reality, and Jinhyuk, who knew about every single thing in the game, took over everything faster than anyone possibly could! “I’ll show you what a true pro is like.”",
        slug:"solo-max-level-newbie",
        _type:"asura",
        ScrapeDate:"Wed, 07 Sep 2022 20:58:48 GMT", 
    },
    {
        title:"Return of the Disaster-Class Hero",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/10/DisasterheroCover01.png",
  shortURL:"https://www.asurascans.com/?p=61390",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-return-of-the-disaster-class-hero/",
  synopsis:"I was the greatest hero on Earth.<br>“But he’s dead. How could the guy we’ve killed come back?”<br>“I dunno. But if he can come back, just let him.”<br>I really came back after 20 years?<br>“Why’re you so surprised? What? Did you do something to hurt your conscience?”<br>You bastards. Just you wait.",
  slug:"return-of-the-disaster-class-hero",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:35 GMT",
    },
    {
        title:"Reformation of the Deadbeat Noble",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/05/Cover1-3.png",
  shortURL:"https://www.asurascans.com/?p=46495",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-reformation-of-the-deadbeat-noble/",
  synopsis:"Airen Parreira is a boy who sleeps to run away from reality. People mocked him, calling him a ‘deadbeat’, but he had no wish to change. Until one day, he dreamt of a swordsman… It was a dream about a talentless man who had been training by swinging his sword for decades.",
  slug:"reformation-of-the-deadbeat-noble",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:27 GMT",
    },
    {
        title:"Swordmaster’s Youngest Son",
    coverURL:"https://www.asurascans.com/wp-content/uploads/2022/04/cover.jpg",
    shortURL:"https://www.asurascans.com/?p=96904",
    MangaUrl:"https://www.asurascans.com/manga/1660333069-swordmasters-youngest-son/",
    synopsis:"Jin Runcandel was the youngest son of Runcandel, the land’s most prestigious swordsman family…<br>And the biggest failure in Runcandel history.<br>He, who was kicked out miserably and came to a meaningless end, was given another chance.<br>“How do you want to use this power?”<br>“I want to use it for myself.”<br>Memories of his past life, overwhelming talent, and a contract with God…<br>The preparations to become the greatest are complete.",
    slug:"swordmasters-youngest-son",
    _type:"asura",
    ScrapeDate:"Wed, 07 Sep 2022 20:58:57 GMT",
    },
    {
        title:"Player Who Can’t Level Up",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/02/Player_That_Cant_Level_Up_Title_Card_-_Barak_kopya.jpg",
  shortURL:"https://www.asurascans.com/?p=38049",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-cant-level-up/",
  synopsis:"Gigyu Kim awakened as a player at the age of 18. He thought his life was on the track to success, climbing ‘the tower’ and closing ‘the gates’… But even after clearing the tutorial, he was level 1. He killed a goblin a day, and he was still level 1. Even after 5 years, he was still level 1. “Who would have thought that this kind of player would exist.” No one knew.",
  slug:"player-who-cant-level-up",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:23 GMT",
    }
  ]
  
  const updates = [{
    title:"Standard of Reincarnation",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/08/standardofReCover03.png",
  shortURL:"https://www.asurascans.com/?p=119179",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-standard-of-reincarnation/",
  synopsis:"The greatest martial family, Samion. Daven, a member of the Samion family, is a one-armed martial soldier without a right arm. Despite the ridicule and contempt he got for only having a left arm, he surpassed the direct line of the Samion family like a genius. However, he got betrayed by his family and parents in the end, thus meeting a poor end. But, he was reincarnated. “I have a right arm?” He had a new family tradition. A naturally gifted body. Experience from his past life. And the god Yulion with him as well. After his reincarnation, everything changed, and a new adventure started.",
  slug:"standard-of-reincarnation",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:52 GMT",
  frontChap1:3,
  frontChap2:2,
  frontChap3:1,
  uploaded:"24 Hours ago",
  },
  {
  title:"Archmage Transcending Through Regression",
  coverURL:"https://asura.gg/wp-content/uploads/2022/10/resource.jpeg",
  shortURL:"https://asura.gg/?p=135816",
  MangaUrl:"https://asura.gg/manga/archmage-transcending-through-regression/",
  synopsis:"Mikhail Walpurgis, the world’s only 9th-circle Archmage, fell in battle due to a damned hero, and managed to cast one final advanced magic spell, <TIME REVERSAL>. As time rewound, he regressed to 20 years ago.<br>“Fine. I’ll just become the hero instead.”",
  slug:"archmage-transcending-through-regression",
  _type:"asura",
  frontChap1:6,
  frontChap2:5,
  frontChap3:4,
  uploaded:"2 Days Ago",
  },
  {
  title:"I Grow Stronger By Eating!",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/05/IMG_8074.png",
  shortURL:"https://www.asurascans.com/?p=47213",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-i-grow-stronger-by-eating/",
  synopsis:"Everyone has a talent of their own.<br>And the talent I have is ‘eating’.<br>A talent that shines much brighter in this world where countless powerful organisms dwell.<br>Feast Devour.<br>Consume the blood and flesh of the strong and make that yours.<br>Even if it’s a dragon, a demon king, or a god!",
  slug:"i-grow-stronger-by-eating",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:57:53 GMT",
  frontChap1:9,
  frontChap2:8,
  frontChap3:7,
  uploaded:"3 Days Ago",
  },
  {
    title:"Reincarnated Escort Warrior",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/07/resource-1.png",
  shortURL:"https://www.asurascans.com/?p=115735",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-reincarnated-escort-warrior/",
  synopsis:"My dream is to become an escort warrior that rides on a cool horse and transports goods. But I’ve got a limp leg and I’m unable to learn decent martial arts. I’ve lived as a porter working odd jobs for the entirety of my life. Until I died because of the mountain bandits that I met during an escort mission.<br>But…<br>‘I became the fourth young master, Lee Jungryong?!’<br>When I died and woke up, I was reborn as the Heavenly Dragon Escort Agency’s infamous good-for-nothing youngest son.<br>The weakling, Lee Jungryong, will become the best escort warrior in this life!",
  slug:"reincarnated-escort-warrior",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:30 GMT",
  frontChap1:5,
  frontChap2:4,
  frontChap3:3,
  uploaded:"3 Days Ago",
  },
  {
    title:"Youngest Scion of the Mages",
  coverURL:"https://asura.gg/wp-content/uploads/2022/10/resource-1.jpeg",
  shortURL:"https://asura.gg/?p=137338",
  MangaUrl:"https://asura.gg/manga/youngest-scion-of-the-mages/",
  synopsis:"It was a ridiculous piece of fiction, one that I’d be ashamed to call a novel. Yet, that was exactly what I was transmigrated into.<br>Larsen Mayton.<br>I became that supporting character, a wretched scoundrel who got purged at the age of 17.<br>Now, as the writer and creator, I shall reshape the world of the character Larsen Mayton.",
  slug:"youngest-scion-of-the-mages",
  _type:"asura",
  ScrapeDate:"Tue, 11 Oct 2022 10:16:14 GMT",
  frontChap1:8,
  frontChap2:7,
  frontChap3:6,
  uploaded:"3 Days Ago",
  },
  {
    title:"The World After The End",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/02/the-world-after-the-end-cover.jpg",
  shortURL:"https://www.asurascans.com/?p=76306",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-the-world-after-the-end/",
  synopsis:"An original story, brought to you by the author of <Omniscient Reader’s Viewpoint>, Author Sing-Shong. This is about a man who didn’t regress when everyone else returned back to the past.<br>Humans were suddenly summoned to become “Walkers”, and they needed to clear the tower to save the world. . . Floor 77: The “Stone of Regression” was discovered.<br>Walkers could now “return” to the past. Slowly, everyone left. . . Humanity’s last hope, “Carpe Diem”, was formed, made up of people who refused to abandon the world. . . The last Walker reached floor 100.<br>He no longer knew what to believe.",
  slug:"the-world-after-the-end",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:59:46 GMT",
  frontChap1:4,
  frontChap2:3,
  frontChap3:2,
  uploaded:"4 Days Ago",
  },
  {
    title:"The Tutorial is Too Hard",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/01/TheTutorialisTooHardCover02.png",
  shortURL:"https://www.asurascans.com/?p=35065",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-the-tutorial-is-too-hard/",
  synopsis:"Gandara’s fusion fantasy novel, ‘The Tutorial is Too Hard’, is now here as a webtoon.<br>One day, amidst a boring life, an invitation message appears before my eyes. [Would you like to enter the tutorial world?]<br>Following it is a difficulty-selection window. [Easy] [Normal] [Hard] [Hell]. I select hell-difficulty without hesitation.<br>And I regret it.<br>I know it said hell-difficulty, but this is just too much.",
  slug:"the-tutorial-is-too-hard",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:59:44 GMT",
  frontChap1:3,
  frontChap2:2,
  frontChap3:1,
  uploaded:"4 Days Ago",
  },
  {
    title:"Rise From The Rubble",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/04/rise.jpg",
  shortURL:"https://www.asurascans.com/?p=43309",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-rise-from-the-rubble/",
  synopsis:"10 years after the night of starfall, city S was destroyed by the biggest recorded monster outbreak in history. Zuo Fan, carrying the name of [A traitor’s son], as well as being the most useless starfall warrior reserve who ran away, awakened the Super Warrior System during a trap disguised as a raid. Since then, he has embarked on the road of success, rising like a meteor. All the while, searching for the truth of his father’s treason amidst the strong opposition, and gradually commencing on the thorny road of saving the world.",
  slug:"rise-from-the-rubble",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:41 GMT",
  frontChap1:6,
  frontChap2:5,
  frontChap3:4,
  uploaded:"5 Days Ago",
  },
  {
    title:"Player Who Can’t Level Up",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2021/02/Player_That_Cant_Level_Up_Title_Card_-_Barak_kopya.jpg",
  shortURL:"https://www.asurascans.com/?p=38049",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-cant-level-up/",
  synopsis:"Gigyu Kim awakened as a player at the age of 18. He thought his life was on the track to success, climbing ‘the tower’ and closing ‘the gates’… But even after clearing the tutorial, he was level 1. He killed a goblin a day, and he was still level 1. Even after 5 years, he was still level 1. “Who would have thought that this kind of player would exist.” No one knew.",
  slug:"player-who-cant-level-up",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:23 GMT",
  frontChap1:9,
  frontChap2:8,
  frontChap3:7,
  uploaded:"5 Days Ago",
  },
  {
    title:"Worn and Torn Newbie",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2020/11/cover-worn.jpg",
  shortURL:"https://www.asurascans.com/?p=28414",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-worn-and-torn-newbie/",
  synopsis:"15 years remain till termination of service. The ending is known only to me. ‘I am a veteran’.",
  slug:"worn-and-torn-newbie",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:59:55 GMT",
  frontChap1:5,
  frontChap2:4,
  frontChap3:3,
  uploaded:"6 Days Ago",
  },
  {
    title:"I Obtained a Mythic Item",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/06/IObtainedaMythicItemCover04.png",
  shortURL:"https://www.asurascans.com/?p=104880",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-i-obtained-a-mythic-item/",
  synopsis:"D-Rank non-combat raider becomes a great enemy of god that will save the world with the strongest restoration item.",
  slug:"i-obtained-a-mythic-item",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:57:54 GMT",
  frontChap1:3,
  frontChap2:2,
  frontChap3:1,
  uploaded:"6 Days Ago",
  },
  {
    title:"Player Who Returned 10,000 Years Later",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/07/Player10000yearsCover02_copy.png",
  shortURL:"https://www.asurascans.com/?p=116341",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-returned-10000-years-later/",
  synopsis:"One day, out of the blue, he falls into hell. All he has with him is his desire to live and predatory powers. From the thousandth hell to the nine thousandth, he‘s devoured tens and hundreds of thousands of demons, and even the seven archdukes bowed down to him. “Why do you wish to go back? Your Highness already has everything in hell.“ “Everything, my ass.“ There’s nothing to eat or enjoy here! Hell’s nothing but desolate land full of terrible demons! “I will return.“ After ten thousand long years, he finally returns to Earth.",
  slug:"player-who-returned-10000-years-later",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:25 GMT",
  frontChap1:7,
  frontChap2:6,
  frontChap3:5,
  uploaded:"6 Days Ago",
  },
  {
    title:"My Daughter is a Dragon!",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/08/resource-1.jpeg",
  shortURL:"https://www.asurascans.com/?p=125540",
  MangaUrl:"https://www.asurascans.com/manga/my-daughter-is-a-dragon/",
  synopsis:"Jihoon was leading a draining life due to his demanding professor, when one day, his daughter fell out of thin air!<br>Thanks to Chaerin, who was as smart and pretty as an elf, things started to look up for him. His skin started to get better, his eyesight and intelligence improved, and he even got taller and more handsome.<br>This was all according to his daughter Chaerin’s plans!<br>Jihoon, who used to be an ordinary science and engineering university student, became a researcher leading the Fourth Industrial Revolution, AI!",
  slug:"my-daughter-is-a-dragon",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:58:14 GMT",
  frontChap1:9,
  frontChap2:8,
  frontChap3:7,
  uploaded:"7 Days Ago",
  },
  {
    title:"Genius of the Unique Lineage",
  coverURL:"https://www.asurascans.com/wp-content/uploads/2022/08/geniusLineageCover01.png",
  shortURL:"https://www.asurascans.com/?p=117672",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-genius-of-the-unique-lineage/",
  synopsis:"I want to be someone who kills invaders<br>__<br>I want to kill invaders and live a happy daily life in a special world.<br>Can’t I just ask for that?<br>Why? Why can’t I do that?<br>People say chasing two different rabbits will make you miss both, but…<br>just don’t miss them.",
  slug:"genius-of-the-unique-lineage",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:57:41 GMT",
  frontChap1:9,
  frontChap2:8,
  frontChap3:7,
  uploaded:"8 Days Ago",
  }]