const updates = [{
    MangaTitle:"Standard of Reincarnation",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/08/standardofReCover03.png",
MangaShortUrl:"https://www.asurascans.com/?p=119179",
MangaUrl:"https://www.asurascans.com/manga/1660333069-standard-of-reincarnation/",
MangaSynopsis:"The greatest martial family, Samion. Daven, a member of the Samion family, is a one-armed martial soldier without a right arm. Despite the ridicule and contempt he got for only having a left arm, he surpassed the direct line of the Samion family like a genius. However, he got betrayed by his family and parents in the end, thus meeting a poor end. But, he was reincarnated. “I have a right arm?” He had a new family tradition. A naturally gifted body. Experience from his past life. And the god Yulion with him as well. After his reincarnation, everything changed, and a new adventure started.",
_id:"standard-of-reincarnation",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:52 GMT",
frontChap1:3,
frontChap2:2,
frontChap3:1,
uploaded:"24 Hours ago",
},
{
MangaTitle:"Archmage Transcending Through Regression",
MangaCover:"https://asura.gg/wp-content/uploads/2022/10/resource.jpeg",
MangaShortUrl:"https://asura.gg/?p=135816",
MangaUrl:"https://asura.gg/manga/archmage-transcending-through-regression/",
MangaSynopsis:"Mikhail Walpurgis, the world’s only 9th-circle Archmage, fell in battle due to a damned hero, and managed to cast one final advanced magic spell, <TIME REVERSAL>. As time rewound, he regressed to 20 years ago.<br>“Fine. I’ll just become the hero instead.”",
_id:"archmage-transcending-through-regression",
_type:"asura",
frontChap1:6,
frontChap2:5,
frontChap3:4,
uploaded:"2 Days Ago",
},
{
  MangaTitle:"I Grow Stronger By Eating!",
  MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/05/IMG_8074.png",
  MangaShortUrl:"https://www.asurascans.com/?p=47213",
  MangaUrl:"https://www.asurascans.com/manga/1660333069-i-grow-stronger-by-eating/",
  MangaSynopsis:"Everyone has a talent of their own.<br>And the talent I have is ‘eating’.<br>A talent that shines much brighter in this world where countless powerful organisms dwell.<br>Feast Devour.<br>Consume the blood and flesh of the strong and make that yours.<br>Even if it’s a dragon, a demon king, or a god!",
  _id:"i-grow-stronger-by-eating",
  _type:"asura",
  ScrapeDate:"Wed, 07 Sep 2022 20:57:53 GMT",
frontChap1:9,
frontChap2:8,
frontChap3:7,
uploaded:"3 Days Ago",
},
{
    MangaTitle:"Reincarnated Escort Warrior",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/07/resource-1.png",
MangaShortUrl:"https://www.asurascans.com/?p=115735",
MangaUrl:"https://www.asurascans.com/manga/1660333069-reincarnated-escort-warrior/",
MangaSynopsis:"My dream is to become an escort warrior that rides on a cool horse and transports goods. But I’ve got a limp leg and I’m unable to learn decent martial arts. I’ve lived as a porter working odd jobs for the entirety of my life. Until I died because of the mountain bandits that I met during an escort mission.<br>But…<br>‘I became the fourth young master, Lee Jungryong?!’<br>When I died and woke up, I was reborn as the Heavenly Dragon Escort Agency’s infamous good-for-nothing youngest son.<br>The weakling, Lee Jungryong, will become the best escort warrior in this life!",
_id:"reincarnated-escort-warrior",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:30 GMT",
frontChap1:5,
frontChap2:4,
frontChap3:3,
uploaded:"3 Days Ago",
},
{
    MangaTitle:"Youngest Scion of the Mages",
MangaCover:"https://asura.gg/wp-content/uploads/2022/10/resource-1.jpeg",
MangaShortUrl:"https://asura.gg/?p=137338",
MangaUrl:"https://asura.gg/manga/youngest-scion-of-the-mages/",
MangaSynopsis:"It was a ridiculous piece of fiction, one that I’d be ashamed to call a novel. Yet, that was exactly what I was transmigrated into.<br>Larsen Mayton.<br>I became that supporting character, a wretched scoundrel who got purged at the age of 17.<br>Now, as the writer and creator, I shall reshape the world of the character Larsen Mayton.",
_id:"youngest-scion-of-the-mages",
_type:"asura",
ScrapeDate:"Tue, 11 Oct 2022 10:16:14 GMT",
frontChap1:8,
frontChap2:7,
frontChap3:6,
uploaded:"3 Days Ago",
},
{
    MangaTitle:"The World After The End",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/02/the-world-after-the-end-cover.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=76306",
MangaUrl:"https://www.asurascans.com/manga/1660333069-the-world-after-the-end/",
MangaSynopsis:"An original story, brought to you by the author of <Omniscient Reader’s Viewpoint>, Author Sing-Shong. This is about a man who didn’t regress when everyone else returned back to the past.<br>Humans were suddenly summoned to become “Walkers”, and they needed to clear the tower to save the world. . . Floor 77: The “Stone of Regression” was discovered.<br>Walkers could now “return” to the past. Slowly, everyone left. . . Humanity’s last hope, “Carpe Diem”, was formed, made up of people who refused to abandon the world. . . The last Walker reached floor 100.<br>He no longer knew what to believe.",
_id:"the-world-after-the-end",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:59:46 GMT",
frontChap1:4,
frontChap2:3,
frontChap3:2,
uploaded:"4 Days Ago",
},
{
    MangaTitle:"The Tutorial is Too Hard",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/01/TheTutorialisTooHardCover02.png",
MangaShortUrl:"https://www.asurascans.com/?p=35065",
MangaUrl:"https://www.asurascans.com/manga/1660333069-the-tutorial-is-too-hard/",
MangaSynopsis:"Gandara’s fusion fantasy novel, ‘The Tutorial is Too Hard’, is now here as a webtoon.<br>One day, amidst a boring life, an invitation message appears before my eyes. [Would you like to enter the tutorial world?]<br>Following it is a difficulty-selection window. [Easy] [Normal] [Hard] [Hell]. I select hell-difficulty without hesitation.<br>And I regret it.<br>I know it said hell-difficulty, but this is just too much.",
_id:"the-tutorial-is-too-hard",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:59:44 GMT",
frontChap1:3,
frontChap2:2,
frontChap3:1,
uploaded:"4 Days Ago",
},
{
    MangaTitle:"Rise From The Rubble",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/04/rise.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=43309",
MangaUrl:"https://www.asurascans.com/manga/1660333069-rise-from-the-rubble/",
MangaSynopsis:"10 years after the night of starfall, city S was destroyed by the biggest recorded monster outbreak in history. Zuo Fan, carrying the name of [A traitor’s son], as well as being the most useless starfall warrior reserve who ran away, awakened the Super Warrior System during a trap disguised as a raid. Since then, he has embarked on the road of success, rising like a meteor. All the while, searching for the truth of his father’s treason amidst the strong opposition, and gradually commencing on the thorny road of saving the world.",
_id:"rise-from-the-rubble",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:41 GMT",
frontChap1:6,
frontChap2:5,
frontChap3:4,
uploaded:"5 Days Ago",
},
{
    MangaTitle:"Player Who Can’t Level Up",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2021/02/Player_That_Cant_Level_Up_Title_Card_-_Barak_kopya.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=38049",
MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-cant-level-up/",
MangaSynopsis:"Gigyu Kim awakened as a player at the age of 18. He thought his life was on the track to success, climbing ‘the tower’ and closing ‘the gates’… But even after clearing the tutorial, he was level 1. He killed a goblin a day, and he was still level 1. Even after 5 years, he was still level 1. “Who would have thought that this kind of player would exist.” No one knew.",
_id:"player-who-cant-level-up",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:23 GMT",
frontChap1:9,
frontChap2:8,
frontChap3:7,
uploaded:"5 Days Ago",
},
{
    MangaTitle:"Worn and Torn Newbie",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2020/11/cover-worn.jpg",
MangaShortUrl:"https://www.asurascans.com/?p=28414",
MangaUrl:"https://www.asurascans.com/manga/1660333069-worn-and-torn-newbie/",
MangaSynopsis:"15 years remain till termination of service. The ending is known only to me. ‘I am a veteran’.",
_id:"worn-and-torn-newbie",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:59:55 GMT",
frontChap1:5,
frontChap2:4,
frontChap3:3,
uploaded:"6 Days Ago",
},
{
    MangaTitle:"I Obtained a Mythic Item",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/06/IObtainedaMythicItemCover04.png",
MangaShortUrl:"https://www.asurascans.com/?p=104880",
MangaUrl:"https://www.asurascans.com/manga/1660333069-i-obtained-a-mythic-item/",
MangaSynopsis:"D-Rank non-combat raider becomes a great enemy of god that will save the world with the strongest restoration item.",
_id:"i-obtained-a-mythic-item",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:57:54 GMT",
frontChap1:3,
frontChap2:2,
frontChap3:1,
uploaded:"6 Days Ago",
},
{
    MangaTitle:"Player Who Returned 10,000 Years Later",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/07/Player10000yearsCover02_copy.png",
MangaShortUrl:"https://www.asurascans.com/?p=116341",
MangaUrl:"https://www.asurascans.com/manga/1660333069-player-who-returned-10000-years-later/",
MangaSynopsis:"One day, out of the blue, he falls into hell. All he has with him is his desire to live and predatory powers. From the thousandth hell to the nine thousandth, he‘s devoured tens and hundreds of thousands of demons, and even the seven archdukes bowed down to him. “Why do you wish to go back? Your Highness already has everything in hell.“ “Everything, my ass.“ There’s nothing to eat or enjoy here! Hell’s nothing but desolate land full of terrible demons! “I will return.“ After ten thousand long years, he finally returns to Earth.",
_id:"player-who-returned-10000-years-later",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:25 GMT",
frontChap1:7,
frontChap2:6,
frontChap3:5,
uploaded:"6 Days Ago",
},
{
    MangaTitle:"My Daughter is a Dragon!",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/08/resource-1.jpeg",
MangaShortUrl:"https://www.asurascans.com/?p=125540",
MangaUrl:"https://www.asurascans.com/manga/my-daughter-is-a-dragon/",
MangaSynopsis:"Jihoon was leading a draining life due to his demanding professor, when one day, his daughter fell out of thin air!<br>Thanks to Chaerin, who was as smart and pretty as an elf, things started to look up for him. His skin started to get better, his eyesight and intelligence improved, and he even got taller and more handsome.<br>This was all according to his daughter Chaerin’s plans!<br>Jihoon, who used to be an ordinary science and engineering university student, became a researcher leading the Fourth Industrial Revolution, AI!",
_id:"my-daughter-is-a-dragon",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:58:14 GMT",
frontChap1:9,
frontChap2:8,
frontChap3:7,
uploaded:"7 Days Ago",
},
{
    MangaTitle:"Genius of the Unique Lineage",
MangaCover:"https://www.asurascans.com/wp-content/uploads/2022/08/geniusLineageCover01.png",
MangaShortUrl:"https://www.asurascans.com/?p=117672",
MangaUrl:"https://www.asurascans.com/manga/1660333069-genius-of-the-unique-lineage/",
MangaSynopsis:"I want to be someone who kills invaders<br>__<br>I want to kill invaders and live a happy daily life in a special world.<br>Can’t I just ask for that?<br>Why? Why can’t I do that?<br>People say chasing two different rabbits will make you miss both, but…<br>just don’t miss them.",
_id:"genius-of-the-unique-lineage",
_type:"asura",
ScrapeDate:"Wed, 07 Sep 2022 20:57:41 GMT",
frontChap1:9,
frontChap2:8,
frontChap3:7,
uploaded:"8 Days Ago",
}]


